# -*- coding: utf-8 -*-
"""Metode Trapezoid

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_mddLN7MeCuOCpfYsMhrlMGXMLfkAqYo

Rachel Savitri - 21120122140111 - Kelas C

Metode Integrasi Trapezoid
"""

import numpy as np
import time

# Fungsi yang akan diintegralkan
def f(x):
    return 4 / (1 + x**2)

# Metode Integrasi Trapezoid
def trapezoid_integration(a, b, N):
    x = np.linspace(a, b, N+1)
    y = f(x)
    h = (b - a) / N #Lebar setiap subinterval
    integral = (h / 2) * (y[0] + 2 * np.sum(y[1:-1]) + y[-1])
    return integral

# Menghitung RMS galat
def rms_error(estimated_pi, true_pi):
    return np.sqrt((estimated_pi - true_pi)**2)

# Nilai referensi pi
true_pi = 3.14159265358979323846

# Variasi nilai N
N_values = [10, 100, 1000, 10000]

# Pengujian dan pengukuran waktu eksekusi
results = []

for N in N_values:
    start_time = time.time()
    estimated_pi = trapezoid_integration(0, 1, N)
    end_time = time.time()

    rms = rms_error(estimated_pi, true_pi)
    exec_time = end_time - start_time

    results.append((N, estimated_pi, rms, exec_time))

# Hasil yang Akan Ditampilkan
for result in results:
    N, estimated_pi, rms, exec_time = result
    print(f"N = {N}, Estimated Pi = {estimated_pi}, RMS Error = {rms}, Execution Time = {exec_time} seconds")